<a href="https://colab.research.google.com/github/harshpandey97/HARSHPANDEY9786/blob/main/Random%20Forest%20Churn%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
print("Pandas imported successfully")

Pandas imported successfully

In [4]:
import numpy as np
print("NumPy imported successfully")

NumPy imported successfully

In [5]:
import sklearn
print("Scikit-learn imported successfully")

Scikit-learn imported successfully

In [6]:
import pandas as pd

df = pd.read_csv("data_for_predictions.csv")

print(df.shape)
df.head()

(14606, 64)

,Unnamed: 0,id,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,months_modif_prod,months_renewal,channel_MISSING,channel_ewpakwlliwisiwduibdlfmalxowmwpci,channel_foosdfpfkusacimwkcsosbicdxkicaua,channel_lmkebamcaaclubfxadlmueccxoimlema,channel_usilxuppasemubllopkaafesmlibmsdf,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw
0,0,24011ae4ebbe3035111d65fa7c15bc57,0.000000,4.739944,0.000000,0.000000,0.0,0.444045,0.114481,0.098142,...,2,6,0,0,1,0,0,0,0,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,3.668479,0.000000,0.000000,2.280920,0.0,1.237292,0.145711,0.000000,...,76,4,1,0,0,0,0,1,0,0
2,2,764c75f661154dac3a6c254cd082ea7d,2.736397,0.000000,0.000000,1.689841,0.0,1.599009,0.165794,0.087899,...,68,8,0,0,1,0,0,1,0,0
3,3,bba03439a292a1e166f80264c16191cb,3.200029,0.000000,0.000000,2.382089,0.0,1.318689,0.146694,0.000000,...,69,9,0,0,0,1,0,1,0,0
4,4,149d57cf92fc41cf94415803a877cb4b,3.646011,0.000000,2.721811,2.650065,0.0,2.122969,0.116900,0.100015,...,71,9,1,0,0,0,0,1,0,0

In [7]:
X = df.drop(columns=["churn", "id", "Unnamed: 0"])
y = df["churn"]

print(X.shape)
print(y.shape)

(14606, 61)
(14606,)

In [8]:
print(X.isnull().sum().sum())

0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(11684, 61)
(2922, 61)

In [10]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

print("Model Trained Successfully!")

Model Trained Successfully!

In [11]:
y_pred = rf.predict(X_test)

y_prob = rf.predict_proba(X_test)[:,1]

print(y_pred[:10])

[0 0 0 0 0 0 1 0 0 0]

In [12]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9099931553730322

In [13]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9099931553730322
Precision: 0.8888888888888888
Recall   : 0.08450704225352113
F1 Score : 0.15434083601286175
ROC AUC  : 0.6947224476502686

In [14]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[2635    3]
 [ 260   24]]

In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      2638
           1       0.89      0.08      0.15       284

    accuracy                           0.91      2922
   macro avg       0.90      0.54      0.55      2922
weighted avg       0.91      0.91      0.87      2922

In [16]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance.head(10))

                    Feature  Importance
5   forecast_meter_rent_12m    0.051749
14               net_margin    0.050190
0                  cons_12m    0.050040
11     margin_gross_pow_ele    0.047125
12       margin_net_pow_ele    0.046884
3         forecast_cons_12m    0.046721
15                  pow_max    0.037678
2           cons_last_month    0.036398
10                 imp_cons    0.031127
22  var_year_price_off_peak    0.030779

In [18]:
feature_importance.head(10)

                    Feature  Importance
5   forecast_meter_rent_12m    0.051749
14               net_margin    0.050190
0                  cons_12m    0.050040
11     margin_gross_pow_ele    0.047125
12       margin_net_pow_ele    0.046884
3         forecast_cons_12m    0.046721
15                  pow_max    0.037678
2           cons_last_month    0.036398
10                 imp_cons    0.031127
22  var_year_price_off_peak    0.030779